### ISSUE TITLE
Plugin doesn't show up in Rack

### ISSUE THREAD

**Issue by ExistentiaVirae** [caoliver/CAOplugs#1]
Under Linux, I cloned the source. It built with only a warning about an unused variable. I did "make install" and verified that the files were in the plugins directory. The modules do not appear in the browser inside Rack.

**Comment by caoliver** [comment]
Oops!  I have two versions of this.  One intended for my use only has a module that references some private patches I've made to Rack, and that change polluted my published module list as given in src/CAOPlugs.{cpp,hpp}.  I fixed that and the unreferenced variable I think.  Please give this a try.

Thanks for the report.  Be well!

**Comment by ExistentiaVirae** [comment]
Tried it, and everything works as expected.
